export const EMAIL = "EMAIL"
export const FIRSTNAME = "FIRSTNAME"
export const LASTNAME = "LASTNAME"
export const FULLNAME = "FULLNAME"
export const PASSWORD = "PASSWORD"
export const CHECK_PASSWORD = "CHECK_PASSWORD"