export { default as alert } from './alert'
export { default as login } from './login'
export { default as product } from './product'
export { default as register } from './register'
export { default as user} from './user'
export { default as welcome} from './welcome'
